[package]
edition = "2018"
authors = ["Guillaume Friloux <guillaume@friloux.me>"]
name = "rompom"
version = "0.0.1"

[dependencies]
checksums = "*"
chrono = "*"
dirs = "*"
getopts = "*"
indicatif = "*"
serde = "*"
serde-xml-rs = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
snafu = "*"
reqwest = { version = "*", features = ["blocking"] }
openssl = { version = '0.10', features = ["vendored"] }
