[package]
edition = "2023"
authors = ["Guillaume Friloux <guillaume@friloux.me>"]
name = "rompom"
version = "0.3.0"

[dependencies]
checksums = "*"
chrono = "*"
dirs = "*"
getopts = "*"
indicatif = "*"
serde = "*"
serde-xml-rs = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
snafu = "*"
reqwest = { version = "*", features = ["blocking"] }
openssl = { version = '*', features = ["vendored"] }


[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
]
